### ISSUE TITLE
Uses RS256 instead of HS256 for JWT signature algorithm

### ISSUE THREAD

**Issue by shawnzhu** [shawnzhu/artifacts-v2#8]
## Today

Now I use HS256 where it uses a single shared key to sign and verify JWT token signature. it is simple but requires configuration option on both `travis-ci/travis-build` and this feature.

## Proposal

Uses RS256 where it uses an RSA private key (available in the context of a Travis build) to sign JWT token, artifacts server will use RSA public key (available when querying Travis Postgres database) to verify JWT token signatures.

The implementation will be more work but no configuration required on neither `travis-build` nor artifacts.

/cc @meatballhat

**Comment by meatballhat** [comment]
I'm in favor of RS256, and configuring the key via env var, which is how we're currently doing it in some pending work in [logs](https://github.com/travis-ci/travis-logs/pull/52) and [job-board](https://github.com/travis-ci/job-board).

**Comment by shawnzhu** [comment]
> I'm in favor of RS256, and configuring the key via env var

So it uses one RSA key pair for Travis CI application instead of single shared key? I was talking about providing per repo JWT signature. E.g., signing JWT token by deployment key of a repo. The downside is, it may not work for public repo since there is no deployment key.

**Comment by meatballhat** [comment]
I think I'm confused about how this JWT is being used.  I was assuming the artifacts service was *verifying* JWTs issued elsewhere by a Travis owned entity.

**Comment by shawnzhu** [comment]
@meatballhat yes. Here are two scenarios:

1. a Travis entity like Travis web UI issues a JWT token for listing artifacts or redirect artifact download request. it requires a given private key.
1. a Travis build issues a JWT token to upload artifact file from Travis build VM. it requires a private key too.

I need to clarify the second scenario because it matters whether configuring a given private key for `travis-ci/travis-build`:
- At first step, I can use the same private key from scenario 1) to implement scenario 2).
- the next step in my mind is using repo specific RSA key pair for issuing JWT token in `travis-ci/travis-build`. But I need to figure out a way for public repo where no deployment key can be found.
