### ISSUE TITLE
manages artifacts schema by sqitch

### ISSUE THREAD

**Issue by shawnzhu** [shawnzhu/artifacts-v2#9]
Now artifact server needs a single table in a PostgreSQL database. It can use the current PostgresSQL database in a Travis CI enterprise deployment or another new database.

/cc @meatballhat @joshk

**Comment by meatballhat** [comment]
My preference is a separate `artifacts` schema managed by sqitch.  Another open source Travis project that's currently doing this is [job-board](https://github.com/travis-ci/job-board).
